### ISSUE TITLE
Consistent way to install linch-pin on different platforms

### ISSUE THREAD

**Issue by arilivigni** [CentOS-PaaS-SIG/linch-pin#145]
We already have a docker image as one solution,  but if someone wants to install this linch-pin other than pip or rpm dependencies don't install in order.

We currently have install.sh but there is a more python way to do the install and do it in order

This should be verified on Fedora, CentOS, RHEL, and Ubuntu (if possible)

**Comment by samvarankashyap** [comment]
@arilivigni : Ansible playbooks can be used to install linchpin , which can be consistent way . But even ansible has some dependencies which needs to be satified specific to operating systems. 
In order to test the builds against multiple operating systems , i would suggest shippable , or Travis CI which deploys open source projects on to different operating systems and reports the status.

**Comment by herlo** [comment]
A simple python method in the setup.py should solve this. I can look into this today.

**Comment by herlo** [comment]
I've been able to get this working with a big adjustment to the setup.py. However, I also introduced several breaking changes to the code. Thus, we'll be addressing this in v1.0.0. In the meantime, the install.sh is there, we just need to document its use.

**Comment by herlo** [comment]
This works in development now.

**Comment by herlo** [comment]
See #170 for RPM functionality
