### ISSUE TITLE
(3) Add or verify support for the 'hostrequire' feature of beaker.

### ISSUE THREAD

**Issue by robled** [CentOS-PaaS-SIG/linch-pin#196]
This feature will allow a Beaker client to specify a list of hostnames which are required for the provisioning task.  This is useful for teams which have reserved a host in Beaker for exclusive use.  Here are the docs from the Beaker project:

https://beaker-project.org/docs/user-guide/job-xml.html

If this feature is currently supported, we should test it and add it to our example topology file.

**Comment by seandst** [comment]
It turns out this probably never worked, because the beaker client handles the "hostrequire" thing kinda specially. The syntax used in examples that I've seen is (in a beaker recipeset in the topology):
```yaml
- hostrequire:
  - beaker.machine.hostname
```

The actual syntax to get this working (again, in a recipeset), is
```yaml
machine: beaker.machine.hostname
ignore_system_status: true
```

If `ignore_system_status` is true, the beaker client lib translates the 'machine' var into the`<hostRequires force="beaker.machine.hostname"/>` XML element required to tell beaker to use the requested host. This works _right now_ in linchpin, so I'm considering the next steps at this point:

* Proper support for beaker's hostRequires feature would be nice, and should be trivial to add, so I might do that as part of this issue.
* Documentation definitely needs to be updated, since the current stable docs use the `hostrequire: - hostname` syntax.
* I'm not yet sure if there are any other effects that come as a result of setting `ignore_system_status` to true, so I'm going to check into that. The whole `machine` specification is actually implemented using hostRequire, and only exists in beaker-client, so we have the option of implementing that interface differently that does not involve `ignore_system_status`.

**Comment by seandst** [comment]
After mulling on this for a little bit and looking into the beaker client code, I have more thoughts.

The second example, where you add the `machine` and `ignore_system_status` vars for passing through to the beaker client, works well enough, but _is not_ how the beaker API works. That's entirely invented by the beaker client. The `ignore_system_status` var must be used in conjunction with `machine`, and only exists in the beaker-client to trigger the `<hostRequires force=...` behavior.

I think it probably makes more sense to handle the "hostrequires" stuff more like the beaker API expects it, and cut out the beaker client lib meddling. I wouldn't go down this path if we weren't already doing just about everything we needed to do with regard to writing out this XML with the exception of _writing out this XML_.

So, I'm planning to implement (and document) "full" hostrequires support as the beaker server API wants it. This will not only include this "force" behavior, but also support the `(key, op, value)` host requirements that beaker supports. Similar to the "force behavior", users can get the `(key, op value)` behavior now, by dropping raw XML into the "hostrequire" key in the topology, e.g. `- '<key op="op" value="value/>'` or some similar yaml-unfriendly (and user-unfriendly) string. Instead, here's what I'm thinking:

```yaml
- hostrequires 
  - force: hostname
  - [key1, op, value1]
  - [key2, op, value2]
```

Note that the key name changes from `hostrequire` to `hostrequires`, with the trailing 's', which brings us closer to the beaker server API by using the actual XML tag documented in the beaker API, and also gets us out of the `hostrequire` namespace that the beaker client uses so there shouldn't be any unexpected side-effects if/when the yaml gets passed through to the beaker client classes for marshaling to XML.

In the event that the nested list syntax is no fun, we can also do something like:

```yaml
- hostrequires 
  - force: hostname
  - key: key1
    op: =
    value: value1
  - key: key2
    op: <=
    value: value2
```

We could potentially go as far as allowing the `(key, op, value)` be a string, e.g. "key1=value1" or key2<=value2, similar to how the "keyvalue" client arg is parsed, but that parsing behavior is not exposed in a reusable way by the beaker client lib. Rather than reimplement it in linchpin, I think it make more sense to be explicit, to the benefit of both usability or the yaml and maintainability of the linchpin code.

**Comment by herlo** [comment]
I like the analysis here. If we're to consider linchpin's maintainability above all else, I love this restructuring. I personally like both yaml options you've mentioned here. The json schema would be the only limitation in my mind. 

WRT xml templating, check out how I did processing of the xml files in the libvirt role for both libvirt_node and libvirt_network. You can use it as a simple model for the template module if it helps.

@herlo

**Comment by seandst** [comment]
Thanks, @herlo. I'll have code up for this shortly showing it, but the XML construction was easy enough inside the bkr_server module. The schema changes were pretty minimal, but I also didn't dig down too deep into the "hostrequires" structure, just specified that "hostrequires" is valid.

**Comment by seandst** [comment]
One minor tweak is that, in looking at [the beaker docs](https://beaker-project.org/docs/user-guide/job-xml.html), it's not clear to me what the valid values for hostRequires elements are, let alone how to declare them as part of a schema. The `(key, op, value)` idea doesn't work with, say, the `<device op = "==" type="network"/>` requirement. The only thing that I see is required would be the "key", which I'm renaming to "tag" since it's actually the hostRequires element created, and this lines up with the beaker client behavior and beaker docs for this filtering mechanism.

Gonna add a bunch of docs for this. :)
