### ISSUE TITLE
Inventory generation inputs seem incomplete

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#232]
On line 8 of [inventory_gen/tasks/main.yml](https://github.com/CentOS-PaaS-SIG/linch-pin/blob/develop/linchpin/provision/roles/inventory_gen/tasks/main.yml#L8), I noticed that we don't process all of the outputs, see line 4 of [output_writer/tasks/main.yml](https://github.com/CentOS-PaaS-SIG/linch-pin/blob/develop/linchpin/provision/roles/output_writer/tasks/main.yml#L4) to line this up. 

Is there a particular reason this is the case? Or did we just decide to not generate inventory for extra things as they are not needed?

**Comment by samvarankashyap** [comment]
@herlo : It's intentional , because inventory generation is with respect to the virtual machine instances only. Whereas the output writer dumps every output that's being generated by the topology resources.
Hope that answers your question.  Inventory generation for resources like s3 buckets and security groups are irrelevant . If we would like to have it we can have them as a part of vars inside inventory file but i feel its not useful for the enduser.

**Comment by herlo** [comment]
It does seem that this was intentional, however, it was not completely clear.  Specifically, I noticed that rax_server was not included in the inventory generator stuff. I figured that one at least needed some attention. Additionally, it did seem that the security groups ones might become useful in an inventory in the future when relating between two types of clouds, though that might be handled differently.

I'm good with leaving this as is for now, save addressing the rax_server bits.

@herlo
